### ISSUE TITLE
Kotlin Gradle plugin version 1.5.20 and higher.

### ISSUE THREAD

**Issue by IvanYue** [gstory0404/file_preview#31]
### 描述
> Kotlin版本与项目版本冲突

### 设备版本
> Flutter 3.10.2  Dart 3.0.2 

### 插件版本
> 1.1.6

### 日志
> 详细的log日志或者截图录屏
```
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':file_preview' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.72
```

**Comment by gstory0404** [comment]
```
file_preview:
  git:
    url: https://github.com/gstory0404/file_preview.git
    ref: v2
```
@IvanYue 
测试分支已升级，暂时无法确认是否引起低版本兼容问题 ，仓库暂不升级
