### ISSUE TITLE
Okhttp冲突

### ISSUE THREAD

**Issue by songsongtao** [gstory0404/file_preview#8]
和其他库或者app的okhttp冲突

**Comment by gstory0404** [comment]
```
file_preview:
    git:
      url: https://github.com/gstory0404/file_preview.git
      ref: 3fd3633c0471369d80d41ebad5041dce24be34df
```
移除了okhttp 试一下
